# @package _global_

defaults:
  - override hydra/sweeper: optuna
  - override hydra/launcher: joblib
  # enable color logging
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

times: 10
T: 100
N: 30
L: 20
mut: 0.02
cross: 0.2
weight_limit: 200
size: [11,6,31,13,10,29,30,35,31,28,15,12,38,43,20,15,45,58,23,34]
importance: [35,34,46,28,38,47,45,55,40,52,44,33,55,63,39,31,60,70,40,43]

work_dir: ${hydra:runtime.cwd}

hydra:
    sweeper:
      direction: maximize
      n_trials: 100
      n_jobs: 10
    launcher:
      n_jobs: 10

    run:
        dir: logs/runs/${now:%Y-%m-%d}/${now:%H:%M:%S}/${hydra.job.override_dirname}
    sweep:
        dir: logs/multiruns/${now:%Y-%m-%d}/${now:%H:%M:%S}/
        subdir: ${hydra.job.override_dirname}

    job:
      config:
        # configuration for the ${hydra.job.override_dirname} runtime variable
        override_dirname:
          kv_sep: '='
          item_sep: '/'